ajout map sur swiper videos
WildCodeSchool/2023-03-JS-Remote-Wild_Impact_P3_Origins pull request #47
Opened 2023-07-13 14:10 UTC by MyMoccca

2023-07-13 14:20 UTC, MrCelsus requested changes

2023-07-13 14:20 UTC, MrCelsus commented on frontend/src/components/HeaderSwiper.jsx
> +  useEffect(() => {
Il faut passer par le fichier connexion

2023-07-13 14:56 UTC, MrCelsus approved these changes

2023-07-17 07:28 UTC, Robin31 approved these changes

2023-07-17 07:28 UTC, merged